var BASE_URL = 'http://localhost:8000';
var LOGIN = BASE_URL + '/admin/login';
var LOGOUT = BASE_URL + '/admin/logout';
var GETUSER = BASE_URL + '/admin/getuser';
var GET = BASE_URL + '/admin/userinfo_get';//修改信息获取地址
var GET2 = BASE_URL + '/admin/userinfo_edit';//修改信息添加地址
var ADD = BASE_URL + '/admin/category_add';//添加文章分类
var ACT_GET = BASE_URL + '/admin/category_search';//获取文章分类
var ACT_EDIT = BASE_URL + '/admin/category_edit';//编辑文章分类